use crate::output::DexOutput;
use crate::writer::DexWriter;

#[derive(Clone, Copy, Debug, Default)]
pub struct AccessFlags(pub u32);

impl AccessFlags {
    pub const PUBLIC: Self      = Self(0x0001);
    pub const PRIVATE: Self     = Self(0x0002);
    pub const PROTECTED: Self   = Self(0x0004);
    pub const NATIVE: Self      = Self(0x0100);
    pub const CONSTRUCTOR: Self = Self(0x10000);

    pub fn with(self, other: Self) -> Self {
        Self(self.0 | other.0)
    }

    pub fn contains(self, other: Self) -> bool {
        self.0 & other.0 == other.0
    }
}

pub struct FieldDef {
    pub name: String,
    /// JNI type descriptor, e.g. "J"
    pub descriptor: String,
    pub access: AccessFlags,
}

/// Bytecode patterns the writer knows how to generate.
pub enum MethodCode {
    /// `<init>(args)V` — invoke-super super.<init>(args), invoke-direct $$init(args).
    Constructor {
        superclass: String,
        /// Descriptor of the super.<init>, e.g. "(Landroid/content/Context;)V"
        super_descriptor: String,
    },
    /// `<init>(args..., long)V` — invoke-super super.<init>(args), iput-wide nativePtr.
    ByoConstructor {
        superclass: String,
        /// Descriptor of super.<init> (no trailing J; that belongs to the BYO ctor only).
        super_descriptor: String,
    },
    /// Private `method$$super(args)V` — invoke-super into the real superclass method.
    SuperAccessor {
        superclass: String,
        method_name: String,
        descriptor: String,
    },
    /// `finalize()V` — invoke-direct $$destroy(), invoke-super Object.finalize().
    Finalize,
}

pub enum MethodEntry {
    /// Declared `native`; contributes an entry to NativeRegistrations.
    Native {
        name: String,
        descriptor: String,
        access: AccessFlags,
        fn_ptr: *mut std::ffi::c_void,
    },
    /// Has generated bytecode.
    Coded {
        name: String,
        descriptor: String,
        access: AccessFlags,
        code: MethodCode,
    },
}

// SAFETY: fn pointers are never called from the writer.
unsafe impl Send for MethodEntry {}
unsafe impl Sync for MethodEntry {}

pub struct ClassDef {
    pub class_name: String,
    pub superclass: String,
    pub interfaces: Vec<String>,
    pub fields: Vec<FieldDef>,
    pub methods: Vec<MethodEntry>,
}

impl ClassDef {
    pub fn compile(self) -> Result<DexOutput, String> {
        DexWriter::compile(self)
    }
}
