// Generated by `cargo reactive` from [package.metadata.reactive].
plugins {
    id("com.android.application") version "{{agp_version}}"
    id("com.reactive.android") version "{{reactive_version}}"
}

android {
    namespace = "{{identifier}}"
    compileSdk = {{compile_sdk}}

    defaultConfig {
        applicationId = "{{identifier}}"
        minSdk = {{min_sdk}}
        targetSdk = {{target_sdk}}
        versionCode = {{version_code}}
        versionName = "{{version}}"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

reactive {
    crateDir.set(file("{{crate_dir}}"))
    packageName.set("{{package}}")
}
