// Generated by `cargo reactive`.
pluginManagement {
{{plugin_include_build}}    repositories {
        mavenLocal()
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
    }
}

rootProject.name = "{{crate_name}}"
{{lib_include_build}}
