#!/bin/bash
# Generated by `cargo reactive`. Xcode build phase: builds the Rust static
# library for every architecture Xcode asks for and merges them.
set -euo pipefail

export PATH="$HOME/.cargo/bin:$PATH"
# Xcode points SDKROOT at the iOS SDK, which breaks build scripts and proc
# macros compiled for the macOS host. The cc crate finds the iOS SDK itself.
unset SDKROOT
export REACTIVE_APP_ID="{{identifier}}"

if [ "$CONFIGURATION" = "Release" ]; then
    PROFILE=release
    CARGO_PROFILE_FLAG=--release
else
    PROFILE=debug
    CARGO_PROFILE_FLAG=
fi

LIBS=()
for ARCH in $ARCHS; do
    case "$PLATFORM_NAME:$ARCH" in
        iphoneos:arm64) TARGET=aarch64-apple-ios ;;
        iphonesimulator:arm64) TARGET=aarch64-apple-ios-sim ;;
        iphonesimulator:x86_64) TARGET=x86_64-apple-ios ;;
        *) echo "error: unsupported platform/arch $PLATFORM_NAME/$ARCH"; exit 1 ;;
    esac
    (cd "{{crate_dir_abs}}" && cargo build --lib -p "{{package}}" --target "$TARGET" $CARGO_PROFILE_FLAG)
    LIBS+=("{{target_dir}}/$TARGET/$PROFILE/lib{{lib_name}}.a")
done

mkdir -p "$DERIVED_FILE_DIR/rust"
lipo -create "${LIBS[@]}" -output "$DERIVED_FILE_DIR/rust/lib{{lib_name}}.a"
