// Generated by `cargo reactive`. The app lives in the Rust static library;
// `reactive_main` is generated by `reactive::app!` and never returns.
#import <UIKit/UIKit.h>

extern int reactive_main(void);

int main(int argc, char *argv[]) {
    return reactive_main();
}
